### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by chipzz**
Bug fixes for ... and rework the converters

### CODE REVIEW

**Comment by glaszig** [comment]
do you remember what "..." was supposed to mean?

**Comment by chipzz** [comment]
It was just a placeholder because I was too lazy to make up a decent commit message at the time. ;) I was fixing various issues across multiple projects.

**Comment by chipzz** [comment]
Ammended the commit message.
One thing of note is that this code might break backward compat in a tiny way, in that you have 2 different ways of parings options that consist of arrays of ips (cfr ipsconverter vs ipsconvertercomma); I changed all options to use ipsconverter (TBH the 2 different ways of passing them didn't make much sense IMO anyway ;) ).

**Comment by glaszig** [comment]
> I was too lazy to make up a decent commit message

yeah, that's why i asked ;)

> I changed all options to use ipsconverter

alright, makes sense.

> TBH the 2 different ways of passing them didn't make much sense IMO anyway

totally.

> might break backward compat in a tiny way

a pitty this thing doesn't come with any sort of unit tests. maybe somebody comes with along :)

thanks for the improvements and fixes. i'll be a bad maintainer and just trust you by the looks of it as i don't use and/or develop this thing anymore.

**Comment by glaszig** [comment]
ping @konobi. objections, maybe?

**Comment by konobi** [comment]
glaszig... tbh, I'm working on a major reworking of how options are handled right now anyways. I suppose i should push what I have currently to a dev branch so others can see what I'm up to at least

**Comment by glaszig** [comment]
oh competition. i'm growing excited. let's see what you have, @konobi.

**Comment by konobi** [comment]
okay... i've pushed to a branch on my repo as "options-redo".

**Comment by konobi** [comment]
Seems like a sensible pull request... I've pulled everything I've been doing into a different repo now.

**Comment by glaszig** [comment]
>  I've pulled everything I've been doing into a different repo now.

i guess you mean [konobi/node-dhcpjs](https://github.com/konobi/node-dhcpjs). looking at node-dhcpjs, it seems quite complete so, i will deprecate this repo and redirect people.

thanks for all your work.

**Pull request closed without merging**
